### ISSUE TITLE
Why is servicePath required?

### ISSUE THREAD

**Issue by willseward** [vfarcic/docker-flow-proxy#131]
My use-case is to use the proxy soley for domain routing. Since I'm required to supply a value for the serviceUrl, the haproxy configuration will end up routing based on the URL.

```
use_backend app_api-be80 if url_app_api80 domain_app_api srcPort_app_api80
```

Could adding `and` to the condition resolve this?

https://www.haproxy.com/doc/aloha/7.0/haproxy/conditions.html

**Comment by vfarcic** [comment]
Is `serviceUrl=/' not working out for you? That should redirect all requests.

**Comment by willseward** [comment]
No, here's a redacted config file:

```text
frontend services
    bind *:80
    bind *:443
    mode http

    acl url_go-demo8080 path_beg /demo
    use_backend go-demo-be8080 if url_go-demo8080
    acl url_app_api80 path /
    acl srcPort_app_api80 dst_port 80
    acl domain_app_api hdr_dom(host) -i demo.com
    use_backend app_api-be80 if url_app_api80 domain_app_api srcPort_app_api80
    acl url_app_flower5555 path /
    acl srcPort_app_flower80 dst_port 80
    acl domain_app_flower hdr_dom(host) -i flower.demo.com
    use_backend app_flower-be5555 if url_app_flower5555 domain_app_flower srcPort_app_flower80

```

Everything redirects to `app_api-be80` due to `url_app_api80` being listed first.

**Comment by willseward** [comment]
Wait, I found the problem. It needs to use `hdr(host)` instead of `hdr_dom(host)` for my use-case.

**Comment by vfarcic** [comment]
From HAProxy docs:
*if no operator is provided between two ACLs, then a logical AND is applied*

As you already saw, the reason why everything is forwarded to the `app_api` service is due to how `hdr_dom` works. In this case, it matches not only `demo.com` domain but also all subdomains. 

From the docs:
*Returns true when one of the headers contains one of the strings either
  isolated or delimited by dots*

I can add a feature that would use `hdr` instead `hdr_dom`. However, before I do that, I'd appreciate if you could try to fix the problem with `aclName`. ACLs are ordered by `aclName`. If not provided, service name is used instead. If you specify `aclName` to, let's say, `xapp_api`, it will be placed below any other ACL (unless there are others that start with `x`) and will be matched only if there is no other match higher in the list. If that doesn't work, I'll add a feature that will let you use `hdr`.

**Comment by willseward** [comment]
https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/ha_proxy.go#L329

It doesn't look like the ACL name in the condition respects `aclName`.

**Comment by willseward** [comment]
Also, thank you for your time. I appreciate it. This service fills an important role that swarm doesn't provide natively.

**Comment by vfarcic** [comment]
Thank you for spotting the problem.

The fix is pushed and available in the latest release. Can you please try it out and let me know how it went?

**Comment by willseward** [comment]
Problem: solved. Thanks for the help.
