### ISSUE TITLE
Rewriting Paths with TCP Mode (proxyfing swarm vizualizer service)

### ISSUE THREAD

**Issue by allamand** [vfarcic/docker-flow-proxy#136]
Hello, 

I'm trying to proxyfi the [swarm vizualiser](https://github.com/ManoMarks/docker-swarm-visualizer) service 

## My DF label conf

This is the label I uses I want to rewrite path because the visualizer service listen on '/', and it works on tcp
```
      labels:
        - com.df.notify=true
        - com.df.distribute=true
#        - com.df.servicePath=/visu/
        - com.df.reqMode=tcp
        - com.df.reqPathSearch=/visu/
        - com.df.reqPathReplace=/
        - com.df.port=8080
        - com.df.srcPort=8080
```

Perhaps it's not possible to rewrite url in TCP mode..

For now I've got an Error

```
proxy_proxy.1.9c5szn2bin7u@node1    | backend visu_visu-be8080
proxy_proxy.1.9c5szn2bin7u@node1    |     mode tcp
proxy_proxy.1.9c5szn2bin7u@node1    |     http-request set-path %!
proxy_proxy.1.9c5szn2bin7u@node1    | (BADINDEX)    server visu_visu visu_visu:8080
```

The output of the configuration gives me
```
...
backend visu_visu-be8080
    mode tcp
    http-request set-path %[path,regsub(/visu/,/)]
    server visu_visu visu_visu:8080
```

## I reproduce it on [play-with-docker](http://play-with-docker.com)

```
docker swarm init --advertise-addr $(hostname -i)
```

Create proxy
```
git clone https://gist.github.com/3b54d37fd85e39cbafa546f6f99c616b.git
docker stack deploy proxy --compose-file 3b54d37fd85e39cbafa546f6f99c616b/proxy-flow.yml
```

Create Service
```
git clone https://gist.github.com/d2d3fb5587629e49c9acb28b994c1638.git
docker stack deploy visu --compose-file d2d3fb5587629e49c9acb28b994c1638/vizualizer.yml
```

It deploy the service so that we can access-it on the port 81 http://ip10_0_2_3-81.play-with-docker.com/ >(**Change IP according to your setup**)

I want also to access it throug the proxy : 
http://ip10_0_2_3-80.play-with-docker.com/visu/
>(**Change IP according to your setup**)

Check the configuration
```
curl http://localhost:8080/v1/docker-flow-proxy/config
```

**Comment by vfarcic** [comment]
There are two problems with the labels you set. The first one is that reqPath should not end with `/`.  It should be:

```
        - com.df.servicePath=/visu
        - com.df.reqPathSearch=/visu
        - com.df.reqPathReplace=/
```

However, that's not a real problem. The issue is that Mano used absolute instead relative paths in his client requests. So, even though the UI now opens through `/visu`, it continues making requests thinking as if it's root. If you inspect it in Chrome console, you'll requests like `/apis/nodes`. The are only two solutions I can think of.

1. Change the code of the visualizer so that it uses relative path (e.g. `apis/nodes`instead `/apis/nodes`). Make a pull request.
2. Use `/` as `servicePath` and add `serviceDomain` as, for example, visu.acme.com.

**Comment by vfarcic** [comment]
@allamand Please let me know if the ticket can be closed or you have a follow-up question.

**Comment by vfarcic** [comment]
Closing the ticket due to inactivity. Feel free to reopen.
