### ISSUE TITLE
redistrubute config on multiple replicas

### ISSUE THREAD

**Issue by lhenry7** [vfarcic/docker-flow-proxy#158]
I have labels:
       - com.df.notify=true
       - com.df.distribute=true
       - com.df.servicePath=/
       - com.df.serviceDomain=mycompany.domain.com
       - com.df.port=80

in my compose yml, but I see this in proxy logs:
2017/03/01 19:02:19 Sending distribution request to http://10.0.0.165:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=80&serviceDomain=mycompany.domain.com&serviceName=my-service&servicePath=%2F
2017/03/01 19:02:19 Processing request /v1/docker-flow-proxy/reconfigure?distribute=false&port=80&serviceDomain=mycompany.domain.com&serviceName=my-service&servicePath=%2F

I was expecting to see distribute=true in logs? Everything works with just one instance of docker-flow-proxy, but if I start a 2nd, it no longer works.

**Comment by vfarcic** [comment]
When the proxy receives a request from the listener with `distribute=true`, it finds the IPs of all the instances and resends the same request to all of them with `distrobute=false` (otherwise it would enter an endless loop). Can you send post the logs of both proxy instances as well as of `swarm-listener`?

Feel free to join http://slack.devops20toolkit.com/. We can have a direct chat over there. If you share your screen, we can probably detect the problem faster.

**Comment by vfarcic** [comment]
@lhenry7 Please let me know if you're still experiencing the problem or we can close this issue.
