### ISSUE TITLE
Ability to set path weight

### ISSUE THREAD

**Issue by n1b0r** [vfarcic/docker-flow-proxy#164]
Similary to **VIRTUAL_HOST_WEIGHT** option of dockercloud-haproxy, we should be able to specify path weight.

This could be needed by [docker-flow-proxy-letsencrypt](https://github.com/n1b0r/docker-flow-proxy-letsencrypt/issues/1).

Thanks.

**Comment by vfarcic** [comment]
There is no need to rename the service name. You can use `aclName` to sort ACLs. All ACLs are sorted by it. If not present, `serviceName` is used instead. So, you can add a label `com.df.aclName=01` and it'll be first on the list.

I think that `aclName` works in a similar way as `VIRTUAL_HOST_WEIGHT`. Please let me know if you disagree.

For Let's Encrypt, since it is so commonly used service, I'm thinking to make an exception. If `.well-known` is present in the path, it'll go to the top no matter what is the `aclName` and  `serviceName`. Please let me know what you think about that.

**Comment by vfarcic** [comment]
Available in the [release 1.234](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.234).

**Comment by vfarcic** [comment]
Please let me know if this solves your problem. Otherwise, please reopen this ticket and we'll look for a different solution.
