### ISSUE TITLE
support for haproxy logging without dfp debugging

### ISSUE THREAD

**Issue by leostarcevic** [vfarcic/docker-flow-proxy#215]
How about we separate haproxy logging from dfp logging by adding  "LOGGING" as a new env only for haproxy logging and leaving DEBUG for dfp logging/debugging?

I can make the necessary changes if you agree on this.

**Comment by vfarcic** [comment]
I think it's the other way around.

DFP outputs logs always while HAProxy logs are enabled only if `DEBUG` is set. Outputting HAProxy logs is very dangerous since it can have serious performance implications while DFP has a relatively low number of log entries and is relatively safe to keep enabled. Besides, users already use DEBUG for outputting HAProxy logs so switching it to LOGGING would potentially break their DFP setup.

**Comment by leostarcevic** [comment]
ok, I keep forgetting about keeping compability for existing users.. lol

whats the best practice for logging with haproxy? keeping it off? where should I log requests instead?

I havent experienced any performance issues by logging to an external syslog service yet but Im sure you are right. I just really need the logs and it was a convenient way of logging everything at one place. any recommendations?

**Comment by vfarcic** [comment]
If you set env. var. `DEBUG` to `true`, all HAProxy logging will be output to `stdout` (preferable way with Docker). From there on, you'd normally send logs (of all services, not only proxy) to ElasticSearch or some other DB.

The problem with logging in HAProxy is that it can easily take more resources to log a request than to forward it. If you don't have a very high load, you won't notice a difference so it's OK if you enable it. The problem start showing only if there are many (many, many) requests. This problem is not directly related with HAProxy but logging in general on high-performance systems. Log what you need, not every transaction or enable debugging only when there is a problem.

In any case, if you set `DEBUG` to `true`, you'll see all the HAProxy logs. You can limit it to only errors with `DEBUG_ERRORS_ONLY`. You can also customize HAProxy logging format with `DEBUG_HTTP_FORMAT` and `DEBUG_TCP_FORMAT`.

**Comment by leostarcevic** [comment]
ok. yes we have logspout taking all container logs to sumologic. I guess we've never had so much traffic to experience any issues, but thanks for the information about the dangers.. closing this now :)
