### ISSUE TITLE
status 404 error

### ISSUE THREAD

**Issue by paulhkhsu** [vfarcic/docker-flow-proxy#249]
I have a docker image paulhkhsu/ztest and internal listen to 8888 port. I did the following but I have difficulty to make proxy work. Can you help me find out why?

1. create network
docker network create --driver overlay proxy
2. create service on proxy network
docker service create --network proxy --name ztest paulhkhsu/ztest
3 run proxy
docker service create --name proxy \
    -p 80:80 \
    -p 443:443 \
    -p 8080:8080 \
    --network proxy \
    -e MODE=swarm \
    vfarcic/docker-flow-proxy
4. re-config service for docker flow proxy
curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=ztest&servicePath=/ztest&port=8888"
5. test and I receive error as below
 curl localhost/ztest
{"timestamp":1495664300562,"status":404,"error":"Not Found","message":"No message available","path":"/ztest"}

Why?

**Comment by vfarcic** [comment]
The message you received does not come from the proxy so it must be from your service. My best guess was that it is not accessible on the path `/ztest` so I made the following test.

```bash
docker network create --driver overlay proxy

# Publish the port 8888 so that the service can be tested without the proxy
docker service create --network proxy --name ztest -p 8888:8888 paulhkhsu/ztest

# Test that the service is indeed reachable through path `/ztest`
curl localhost:8888/ztest

# The output is: `{"timestamp":1495667406795,"status":404,"error":"Not Found","message":"No message available","path":"/ztest"}`

# Check whether the service is accessible through root path
curl localhost:8888

# The output is `Greetings from Spring Boot!`

# Remove the port of the service. We don't need it any more since we'll reconfigure the proxy
docker service update --publish-rm 8888 ztest

# Create the proxy service
docker service create --name proxy -p 80:80 -p 443:443 -p 8080:8080 --network proxy -e MODE=swarm vfarcic/docker-flow-proxy

# Reconfigure the proxy with the root path instead
curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=ztest&servicePath=/&port=8888"

# Confirm that it works
curl localhost
```

The question is what you'd like to do? Normally, you don't want to use the root path only since no other services will be able to operate alongside it. If you want to rewrite `/ztest` to `/` (it's what your service expects even though it's a bad practice), then the command should be as follows.

```bash
# Reconfigure the proxy with the root path instead
curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=ztest&servicePath=/ztest&port=8888&reqPathSearch=/ztest&reqPathReplace=/"

# Confirm that it works
curl localhost/ztest
```

... or, you might want to use a  subdomain...

```bash
curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=ztest&servicePath=/ztest&port=8888&serviceDomain=ztest.acme.com"

# Confirm that it works
curl ztest.acme.com
```

There are many other combinations that can be used. The first step would be for you to tell me what you're trying to accomplish or, even better, go through tutorials in http://proxy.dockerflow.com/swarm-mode-auto/ and http://proxy.dockerflow.com/swarm-mode-stack/ since they explain some of the most commonly used practices.

Please let me know if we can close this issue or you have some follow-up questions.

**Comment by paulhkhsu** [comment]
thank you.
I use the concept in this tutorial.
https://technologyconversations.com/2016/08/01/integrating-proxy-with-docker-swarm-tour-around-docker-1-12-series/

Why in tutorial
curl "$(docker-machine ip node-1):8080/v1/docker-flow-proxy/reconfigure?serviceName=go-demo&servicePath=/demo&port=8080"

why can work with curl host/demo/hello

**Comment by paulhkhsu** [comment]
Sorry, I figure out, I don't give application context for my ztest application. I thought servicePath=/ztest is the service name in docker swarm. but it is context path. 
Very good comment thanks.

I have another question, how to do HA for two docker-flow-proxy. I mean two proxy on two node. I know you use peer command if you use proxy outside swarm mode.

**Comment by paulhkhsu** [comment]
Hi Varcic,

IF I do 
docker service create --network proxy --name ztest  paulhkhsu/ztest
docker service create --network proxy --name ztest1 paulhkhsu/ztest

docker service create --name proxy \
    -p 80:80 \
    -p 443:443 \
    -p 8080:8080 \
    --network proxy \
    -e MODE=swarm \
    vfarcic/docker-flow-proxy


curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=ztest&servicePath=/ztest&port=8888&reqPathSearch=/ztest&reqPathReplace=/"
curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=ztest1&servicePath=/ztest1&port=8888&reqPathSearch=/ztest1&reqPathReplace=/"

# this work
curl localhost/ztest
# this not work ??? why
curl localhost/ztest1

**Comment by vfarcic** [comment]
It doesn't work because the proxy is checking whether `servicePath` value matches the beginning of the request path. For example, if `servicePath=/something` it would match requests `/something`,  `something/else`, `something1234`, and so on. In other words, both `curl` requests would end up in `ztest` service.

To accomplish what you're trying to do you'd need to think about ordering. The proxy evaluates rules sequentially and uses the first one that is a match. The rules are ordered alphabetically through `aclName` param. If that param is not set (and in your case it's not), it defaults to the name of the service. So, `ztest` service is above  `ztest1` and, using those `curl` examples, catches both requests. What you can do is to add something like `aclName=01-ztest1` to the `ztest1` service. Since `01-ztest1` would be before `ztest`, it would be evaluated first. When you send the first request to `localhost/ztest` the proxy would evaluate `01-ztest1` and it would not match. Then it would go for the second set of rules, it would match, and the request would be forwarded to the service `ztest`. The second reqest to `localhost/ztest1` would go through the same process but the first set of rules would be a match and the request would be forwarded to the service `ztest1`.

Please let me know if this answers your question.

**Comment by paulhkhsu** [comment]
Thank you, Sorry I don't quit understand
I think my problem is how can I configure proxy as below in order to make curl localhost/ztest and curl localhost/ztest1 work. or it is not possible. I just like to see if I have one image run two swarm containers with different service name, how can I set up proxy to access them separately.

# curl localhost/ztest work with this
curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=ztest&servicePath=/ztest&port=8888&reqPathSearch=/ztest&reqPathReplace=/"

# curl localhost/ztest1 receive 404 error
curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=ztest1&servicePath=/ztest1&port=8888&reqPathSearch=/ztest1&reqPathReplace=/"

**Comment by vfarcic** [comment]
Here it goes.

```bash
docker network create --driver overlay proxy

docker service create \
    --network proxy \
    --name ztest \
    paulhkhsu/ztest

docker service create \
    --network proxy \
    --name ztest1 \
    paulhkhsu/ztest

docker service create \
    --name proxy \
    -p 80:80 -p 443:443 -p 8080:8080 \
    --network proxy \
    -e MODE=swarm \
    vfarcic/docker-flow-proxy

curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=ztest&servicePath=/ztest&port=8888&reqPathSearch=/ztest&reqPathReplace=/"

curl localhost/ztest

curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=ztest1&servicePath=/ztest1&port=8888&reqPathSearch=/ztest1&reqPathReplace=/&aclName=01-ztest1"

curl localhost/ztest1
```

The only real difference from what you did is the addition of the `aclName=01-ztest1` parameter. Since services are ordered and evaluated alphabetically and `ztest` uses the path `/ztest` that matches both, putting the `ztest1` above `ztest` allows the proxy to evaluate it before it reaches `ztest`.

Normally, you would not need `aclName` since your services probably have a more unique paths. If (or when) that is not the case, you can reorder ACLs using `aclName` which defaults to `serviceName`.

Please let me know if this answers your question.

As a side note, did you try using [Docker Flow Swarm Listener](http://swarmlistener.dockerflow.com/)? It would remove the need for sending manual reconfigure requests to the proxy.

**Comment by paulhkhsu** [comment]
I agree with you usually applications have more unique paths. But the following case are reasonable.
For example, I use spring boot to create two apps, both has '/' as root context. no 'server.contextPath' in application.property file and both use port 8080 as default.
App1 has path '/' for home and '/customer' for one api. and the image name is paulhkhsu/app1
App2 has path  '/' for home and '/inventory' for on api, and the image name is paulhkhsu/app2.

Like you specify we create two service in docker swarm, but give service name not same as image

docker service create \
    --network proxy \
    --name abc \
    paulhkhsu/app1

docker service create \
    --network proxy \
    --name xyz\
    paulhkhsu/app2

How to do reconfigure in order for the following work? Do I need aclName? 
curl localhost/aaa                     ---》this map to abc:8888 service name in swarm
curl localhost/aaa/customer
curl localhost/zzz                 ---> this map to xyz:8888 service name in swarm
curl localhost/zzz/inventory


My confusion is the following api. serviceName={the service name in swarm when use docker service create?}, servicePath={the root context of service name in swarm?}, port={service port?}
curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=abc&servicePath=/&port=8888"

I may need to read more detail for how to use the docker-flow-proxy but I can't find a one with more detail and more examples. Please forget me I am not expert on docker-flow-proxy so far.

**Comment by vfarcic** [comment]
To accomplish the `curl` examples you should set `servicePath` of `abc` to `/aaa` and use `/zzz` for the service `xyz`. If you use only `servicePath`, the proxy would forward `/aaa` to `/aaa` of the service `abc`. If you'd like to forward `/aaa` to `/` then you'd need to set `reqPathSearch=/aaa` and `reqPathReplace=/`.

We can have a chat through Skype or HangOuts and go through the core principles together.

**Comment by vfarcic** [comment]
I forgot to mention is that you do not need to use `aclName` when combination of paths and domains is unique. In the `curl` examples you posted, they are unique.

**Comment by vfarcic** [comment]
The command should be:

```bash
curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=abc&servicePath=/aaa&port=8888"
```

In the request you posted, you switched `serviceName` and `servicePath` values. `serviceName` is the same as the `--name` argument when you're creating the service. `servicePath` is the minimum path of a request. So, `/aaa` would match `acme.com/aaa`, `acme.com/aaabbbccc`, and  `acme.com/aaa/something/else`.

> Am I correct? Because I thought serviceName is abc in 'abc:8888/' and servicePath is / in 'abc:8888/' and port is 8888 in 'abc:8888/' before. I don't know how can I specify aaa in command before.

You're correct that the `serviceName` is `abc`. While `servicePath` can be `/`, it is better to put `/aaa` since that will not be in conflict with other services.

**Comment by paulhkhsu** [comment]
Thanks,
I understand now. servicePath is the redefined (mapping URL) path for outside access.
serviceName must same as --name and servicePath is curl localhost/xxx as xxx part. It is better give more unique match pattern when assign value to servicePath.

**Comment by vfarcic** [comment]
That's correct @paulhkhsu . I'll do my best to make the documentation clearer.

Please let me know if we can close this issue.

**Comment by paulhkhsu** [comment]
I appreciate your help. I understand your application is trying to help user to create and configure HAProxy inside swarm so it can be scale up/down easily. If you run HAproxy outside swarm, you don't benefit scale up/down provided by swarm. Only problem is that most user like to have more detail information in order to use the product more thorough. Please close the case and let us know if you have more detail document

**Comment by paulhkhsu** [comment]
Sorry, one more question. If I like to persistent what the configuration change to HAproxy, do I just mount some folder to /cfg/.... folder in container?

**Comment by paulhkhsu** [comment]
I am sorry, I just did this test, but it still not working, what I did wrong?
docker service create --network proxy --name abc paulhkhsu/ztest
docker service create --network proxy --name xyz paulhkhsu/ztest
docker service create --name proxy -p 80:80 -p 443:443 -p 8080:8080 --network proxy -e MODE=swarm vfarcic/docker-flow-proxy
curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=abc&servicePath=/aaa&port=8888"
curl localhost/aaa <-------- return 404

same as this, not working
curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=xyz&servicePath=/zzz&port=8888"
curl localhost/zzz<-------- return 404

**Comment by vfarcic** [comment]
Can you try the command that follows?

curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=abc&servicePath=/aaa&port=8888&reqPathSearch=/aaa&reqPathReplace=/"

**Comment by paulhkhsu** [comment]
I did the following, all work, thanks.
docker service create --network proxy --name abc paulhkhsu/ztest
docker service create --network proxy --name xyz paulhkhsu/ztest
docker service create --name proxy -p 80:80 -p 443:443 -p 8080:8080 --network proxy -e MODE=swarm vfarcic/docker-flow-proxy

curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=abc&servicePath=/aaa&port=8888&reqPathSearch=/aaa&reqPathReplace=/"
curl localhost/aaa
curl localhost/aaa/api

curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=xyz&servicePath=/zzz&port=8888&reqPathSearch=/zzz&reqPathReplace=/"
curl localhost/zzz
curl localhost/zzz/api

**Comment by vfarcic** [comment]
I'm glad it worked out :)
