### ISSUE TITLE
proxy config of service with long delay making ports active

### ISSUE THREAD

**Issue by lhenry7** [vfarcic/docker-flow-proxy#278]
I have a couple services that have a long initialization period, and as such, the defined com.df.srcPort is opened after a long (50-60s) delay.

Seems like the auto-configuration process misses this. If the flow-listener and flow-proxy are started after the slow initializing service is already started, it auto-configs just fine.

Is there anyway to accommodate a service with a long init time before it opens the port?

**Comment by lhenry7** [comment]
postscript: Tried the REPEAT_RELOAD=true (with RELOAD_INTERVAL=10000) and it seems to work better. I'll do some more testing with these options.

**Comment by lhenry7** [comment]
Figured out that on this test environment, I was loading flow-proxy:latest, which is where config issues came. If I go back to at least Ver 1.368, it configures even these services. Not sure at what version exactly it stops working, I can try a few others if it will help.

**Comment by lhenry7** [comment]
By process of elimination, Ver 1.393 works, Ver 1.415 and 1.419 no longer do. I was originally testing because I experience issue #266 as well. Some intermittent case where the configs not only get out of sync, even re-starting services doesn't get it back. Do you think introducing a status check on the servers help?

**Comment by vfarcic** [comment]
@lhenry7 I went through the commits since 1.393 and did not see anything "obvious" that could cause the issue. It would help a lot if you can narrow it down to a specific version (no necessarily the official release). If I know which release (from Docker Hub) broke it, it should be fairly straightforward to find the cause. Do you think you'd have time to narrow it down?

**Comment by lhenry7** [comment]
I only see releases 1.425 and 1.419 since 1.393 in https://github.com/vfarcic/docker-flow-proxy/releases

**Comment by vfarcic** [comment]
Those are the official releases. I make them only when a new feature is added. Every commit (e.g. bug fixes, refactoring, documentation, and so on) is built and released to Docker Hub (https://hub.docker.com/r/vfarcic/docker-flow-proxy/tags/).

**Comment by lhenry7** [comment]
Looks like 1.413 will configure the service, 1.415 does not (consistently). This is of course separate from the issue where after running for a while, after many services are stopped and restarted, the proxy seems to get lost. Even though the config file looks good, the proxy returns 503 or even worse, sends the request to the wrong service.

**Comment by vfarcic** [comment]
That's great @lhenry7 . It narrows it down to only a handful of commits. I have one more request... Do you have a stack I could use to reproduce it? Since all releases work with the services I'm running in my cluster, I suspect it's a specific combination that triggers the issue.

**Comment by lhenry7** [comment]
Unfortunately, my stack is pretty specific to my environment, it downloads a bunch of config instructions from my S3 bucket and so on. I can try and construct something that mimics the delay, just some nginx with a delayed start might do.

**Comment by vfarcic** [comment]
That would be great :)

**Comment by JesusPerez** [comment]
I am  using lates version from github repo and I get same results as @lhenry7 ... 503 always always come up first, proxy is in master and services are running in workers, I also share same status in terms of stack and services. If @lhenry7 can construct something I can test it or add more thing if it can help somehow. Probably there is something missing in haproxy or nginx services config, but I really do not know, services are up and running but finally I have to restart proxy stack to get it running again.

**Comment by JesusPerez** [comment]
For instance I am using "mode: host" to get proxy forwarded IP but before I used results are almost the same. Do you have a timeout before goes into 503 because sometimes, specially at the beginning, services has to be resolved, nginx services has to start, load fpm, caches, etc.?

**Comment by vfarcic** [comment]
@JesusPerez I haven't tried it with the mode `host` so I'm not sure what is the behavior. Also, none of the services I run take more than 10 seconds to start so I haven't hit the same problem myself. Let's wait for a stack from @lhenry7 (unless you have one at hand @JesusPerez ). Once there is a way for me to reproduce it, I'm sure the fix will be fairly easy.

**Comment by JesusPerez** [comment]
@vfarcic thanks for your answer, I setup something you can download here: https://drive.google.com/file/d/0B1PATehzS00NT3FmRUxMYVcwcWs/view?usp=sharing
It is using SSL certificates, but I did include one, I think you can get a full idea, it has a WP version ready to install. I hope this can help somehow.
I am running docker swarm mode 17.05.0-ce on alpine 3.6.2 servers
If you need something else just let me know.

**Comment by JesusPerez** [comment]
Another thing that I can post is that before last flow proxy update in many cases restart is need it for  services and proxy stack recovery but today I have got a call from one customers who is getting again 503 with php WP ajax update calls and also with a simple html page redirect ... so that is why I think it looks like a timeout issue,  if I get into proxy docker instance I can ping and get nginx-services responses from worked nodes but proxy fallback into 503 error, restart proxy stack solve problem.

**Comment by lhenry7** [comment]
So my simple approach didn't give the desired outcome, so I have a better on that is closer to my actual use case. Here are a couple compose files, one for how I start proxy and another for how I start my service. It is a varnish instance that registers with proxy, and reverse proxies to a simple nginx service that just displays the default welcome page.

[compose-files.zip](https://github.com/vfarcic/docker-flow-proxy/files/1136392/compose-files.zip)

**Comment by lhenry7** [comment]
I start proxy first, then the nginx stack, which does not register. If I start nginx stack first, then the proxy stack 2nd, it does.

**Comment by vfarcic** [comment]
@lhenry7 There was a problem with the stack. It had `- com.df.serviceDomain=default.test.com` (no index) and `- com.df.servicePath.1=/` (with index). DFP took the domain and thought that you don't want to use index. Further on, it complained that there is no `port` which is true since there is `- com.df.port=80` but not `- com.df.port.1=80`.

One of the relatively recent requests was to allow indexing of `serviceDomain` parameter.

I'm not sure whether that's the original cause of your problem but, for this stack, it is. DFP managed to configure itself as soon as I changed to `- com.df.serviceDomain.1=default.test.com`.

Can you please check whether that's what's causing your issues. If not, we still need to figure out how to reproduce it :(

**Comment by vfarcic** [comment]
@lhenry7 In the mean time, I'll implement https://github.com/vfarcic/docker-flow-proxy/issues/286. It should be done no matter whether your issue is what I described or something else.

**Comment by lhenry7** [comment]
Yes, adding .1 to the serviceDomain does cause it to register. Funny starting the service first then the proxy, it does register and works afterwards.

I guess my initial problems may still exist, after many service restarts, proxy either throws 503 or sends requests to wrong service.

**Comment by vfarcic** [comment]
@lhenry7 Can you continue working on creating a stack that will reproduce it while, in parallel, I fix the problem with `serviceDomain`.

**Comment by lhenry7** [comment]
Actually this will be much harder to reproduce, everything works for weeks, then suddenly doesn't. Are there any troubleshooting steps or data collection I can do and pass to you that would help once the problem occurs?

**Comment by vfarcic** [comment]
I wish there were. At the moment, the only source of info are logs and configs. If you cannot reproduce it, make a Gist with logs and DFP configs and I'll check whether I can spot anything.

**Comment by lhenry7** [comment]
The service registration error occurred again. The sequence of events are: We start/restart some service, and notice no request get to any service. We check the configs, and 1 (of 2 total) proxy has an updated config, the other doesn't. When we check the logs of the proxy instance, we see it in some loop sending the reconfigure request. Stopping and restarting the proxy and listener stack doesn't fix the problem, the looping behavior resumes. We then have to stop all services (which has no effect on the proxies, they just continue looping), then we stop the proxy stack. restarting from point 0 seems to be the only way to recover from this.  The haproxy configs form the 2 proxy instances and the json logs from 1 proxy are attached. Hope this gives some clue. 
[flow-proxy.zip](https://github.com/vfarcic/docker-flow-proxy/files/1141924/flow-proxy.zip)

**Comment by vfarcic** [comment]
@lhenry7 Judging by the logs one of DFP replicas could not reach one of your services. In all the cases, the problem is in reaching `stage-cso-digital_app`. That's quite strange since I can see that you have quite a few services in your cluster but only that one is not reachable.

Can you confirm that both proxy replicas are accessible as well as the `stage-cso-digital_app` services? The commands would be:

From inside DFP replica 1 container:

```bash
apk add --update drill
drill swarm-listener
drill proxy
drill tasks.proxy
drill stage-cso-digital_app
drill tasks.stage-cso-digital_app
```

Please repeat the same commands from DFP replica 2 and from DFSL.

**Comment by lhenry7** [comment]
going to close this one since serviceDomain is fixed. I still think I experience #266 and maybe #245 as well though
