### ISSUE TITLE
TLS termination

### ISSUE THREAD

**Issue by je-al** [vfarcic/docker-flow-proxy#281]
Hi, I've been reading through the documentation but can't seem to find a way to define TLS termination for frontends other than the default HTTPS one, since we already have support for TLS, and multiple certs, and SNI; this doesn't seem that big of an addition, is this even supported?

What I'd like is to be able to define several listeners (through srcPort / port, since these would be "TCP" services, hence the inability to split the requests using hostnames) each of which would terminate TLS (using the certificate that matches their serviceDomain?, it's actually more akin the "SNI" reqMode, since for "clashing" ports it could/should route based on that).

**Comment by vfarcic** [comment]
That sounds like a good idea. The only problem is that I don't think I'll be able to work on this within the next 10 days. Would you like to give it a try with a PR? Also, maybe @faisyl can help since he did SNI and this would be similar.

**Comment by faisyl** [comment]
Do you have an example ha-proxy configuration that you could share?

**Comment by je-al** [comment]
```

**Comment by je-al** [comment]
@faisyl oh, it's rather straightforward, what I'm trying to accomplish is something like:
```
frontend mqtts
    bind 0.0.0.0:8883 ssl crt /etc/ssl/private/cert.pem ciphers ...
    mode tcp
    option clitcpka
    option tcplog
    timeout client 180000ms
    default_backend mqtts-tls-backend

backend mqtts-tls-backend
    mode tcp
    option srvtcpka
    option tcp-check
    timeout server 180000ms
    server mqtts-tls-backend-1 1.mqtt.prd.example.local:1883 check fall 3 rise 2 inter 10s check on-mark
```
thought, it does need a way to associate the correct cert with the service (when not reusing the current "default" one), which might or might not be done by "overloading" the `serviceDomain` parameter.

**Comment by faisyl** [comment]
Reading thru the HA-Proxy documentation, it appears to me that ha-proxy will present the correct certificate if you are terminating it based on the SNI and routing to the backend service should be straightforward based on SNI. See the example here:

https://serverfault.com/questions/560978/configure-multiple-ssl-certificates-in-haproxy
In your case I believe all you are missing in the configuration is SNI switching. SNI based routing is already supported in docker-flow-proxy. Might require small tweaks to allow TLS termination. I can't validate behavior because I don't have multiple certs to test with.

Based on this assumption, I think you should be able to get it work with minimal changes in code. 
If you have a multiple backend example that you actually use, I'll try and work out how to configure docker-flow-proxy to generate the config you need.

**Comment by opHASnoNAME** [comment]
Any suggestions how to get this working? We want to do TLS Termination for RABBITMQ-MQTT on Flow-Proxy. If someone got this working, i would love to read how.

**Comment by vfarcic** [comment]
@opHASnoNAME I'm on vacations and won't be able to work on this issue until the next week. Please post your question on https://devops20.slack.com/. If you're not already a member, please register through http://slack.devops20toolkit.com/ .

If no one helps on Slack, please post your stacks so that I can reproduce the same setup you're using as well as a command I could use to test that DFP is indeed integrated with RabbitMQ.

Before we proceed with all that, please confirm my assumptions that RabbitMQ is running inside a Swarm cluster and needs to be accessed by services that are not in the same cluster. If that's not true and both RabbitMQ and services that need to access are in the same Swarm cluster, DFP is not needed. They should communicate through Overlay network.

**Comment by opHASnoNAME** [comment]
Hi, we want to publish Port 15672 via SSL: This works fine. As Second service we want to publish MQTT with TLS Termination on HA-Proxy.

Configures as reqMode=tcp , and reachable from the "outside", this works but i have no idea how to set a SSL certificate for Port 1883. Like the example from Je-Al.

But enjoy your holidays, may be we find a way tomorrow. 

Great product!

**Comment by je-al** [comment]
@opHASnoNAME no way to do it right now...
I did take a look at the code, but found out that a big refactoring was needed in order to support what I had in mind. @faisyl's proposal is less traumatic (and fulfills my current needs), but wouldn't work if you actually need to support more than one certificate (i.e. you don't have a wildcard cert), because not all (or, maybe we could say no one but browsers) clients implement SNI, which makes it necessary to be able to indicate which cert to use with a particular `frontend`

**Comment by opHASnoNAME** [comment]
Thanks, i am not sure.. but does we need more than one certificate? The Domain is the same for Webfrontend and one for MQTT (only other Ports). But another approach for us is the use MQTT with RabbitMQ and TLS terminal at Rabbit.

**Comment by je-al** [comment]
@opHASnoNAME that's what I'm saying, if you don't need support for more than one certificate, the solution proposed (as in, not yet implemented) by @faisyl in https://github.com/vfarcic/docker-flow-proxy/issues/281#issuecomment-316266268 would work...

**Comment by faisyl** [comment]
I think the easiest way to get this moving would be to setup a standalone haproxy instance, configure it to talk to your backend services the way you would expect it to work and make sure that it does. Once that's done, if you can post the config here, it should be straightforward to determine if docker-flow-proxy needs any changes to get your specific configuration to work.

**Comment by vfarcic** [comment]
Closing the issue due to inactivity. Please reopen it if you'd like to continue working on it.

**Comment by arrisde** [comment]
I'd also be interested in a solution to this. My use case is an IoT-backend for data collection from sensor devices that supports multiple types of protocols (websocket, MQTT, AMQP) all with TLS encryption that ideally I'd like to terminate using docker-flow-proxy. 
It seems that in order to do this I'd need to be able to configure certificates on a per-service base which isn't possible currently, right?

**Comment by faisyl** [comment]
If all services that you are trying to multiplex on a single port use HTTP (over TLS), then you can route using HTTP headers as you currently do in your #430 example. The termination and certificates to use will depend on the FQDNs in use. If you are using a single FQDN and single certificate, that will also work. The SNI base routing is useful if you wish to multiplex non-HTTP TLS traffic, your client is new enough to set the SNI field and are prepared to either:

1. Use a wildcard certificate with different prefixes as service endpoints which will be routed via SNI.  For example, with a single *.mydomain.com, you can use service backends like so: ws.mydomain.com and mqtt.mydomain.com etc. You set up DNS to point both FQDNs to the same address as the DFP frontend.
2. You use different certificates or certificates with multiple SAN entries that point to independent service endpoints. For example, you have a certificate that's valid for mqtt.mydomain.com and a SAN entry as ws.myotherdomain.com or suchlike. DNS points to the same DFP frontend for both FQDNs. For different certificates, see the DFP documentation on how to set up.

Apart from the certificate configuration, both 1 and 2 above can be routed via SNI. There's a new SNI configuration section on the DFP page. To sum up. Don't bother with SNI unless you wish to route non-HTTP traffic. AFAIK you can't mix SNI and header-based routing together. If you really need to do that, then use 2 separate ports, one for HTTP and the other for non-HTTP, both terminated using TLS.

**Comment by arrisde** [comment]
I'm mostly interested in the non-HTTP TLS case at the moment. So if I understand correctly, you are saying that if I have a certificate satisfying either 1. or 2., DFP can be used with this certificate to terminate TLS for multiple non-HTTP services, either running on separate ports or routed via SNI (if supported by clients)? 

I'd be curious to see an example for this. As far as I understand, the SNI tutorial in the DFP docs does not really apply to this case since it does SSL-passthrough.

**Comment by faisyl** [comment]
That's right. The DFP docs don't cover that scenario, but I think it should work with a cert in place as well. I'll try and test out this scenario and post results here.
