### ISSUE TITLE
servicePath order should be longest first

### ISSUE THREAD

**Issue by lhenry7** [vfarcic/docker-flow-proxy#292]
Here is a snippet from the HAproxy.cfg:

frontend services
    bind *:80
    bind *:443
    mode http

    acl url_dev-digital_app80 path_beg /digital
    acl srcPort_dev-digital_app80 dst_port 80
    acl url_dev-digital_app443 path_beg /digital
    acl srcPort_dev-digital_app443 dst_port 443
    acl domain_dev-digital_app hdr(host) -i dev.geready.com
    use_backend dev-digital_app-be80 if url_dev-digital_app80 domain_dev-digital_app srcPort_dev-digital_app80
    use_backend dev-digital_app-be443 if url_dev-digital_app443 domain_dev-digital_app srcPort_dev-digital_app443
    acl url_dev-digitalproductlifecycle_app80 path_beg /digitalproductlifecycle
    acl srcPort_dev-digitalproductlifecycle_app80 dst_port 80
    acl url_dev-digitalproductlifecycle_app443 path_beg /digitalproductlifecycle
    acl srcPort_dev-digitalproductlifecycle_app443 dst_port 443
    acl domain_dev-digitalproductlifecycle_app hdr(host) -i dev.geready.com
    use_backend dev-digitalproductlifecycle_app-be80 if url_dev-digitalproductlifecycle_app80 domain_dev-digitalproductlifecycle_app srcPort_dev-digitalproductlifecycle_app80
    use_backend dev-digitalproductlifecycle_app-be443 if url_dev-digitalproductlifecycle_app443 domain_dev-digitalproductlifecycle_app srcPort_dev-digitalproductlifecycle_app443

Because the hostname is the same, the /digitalproductlifecycle path should be before the /digital path, otherwise /digital catches everything. This is using flow-proxy V1.368, but I was sure this part was working before this version?

**Comment by vfarcic** [comment]
ACLs are ordered alphabetically by `aclName` parameter. If not provided, `serviceName` is used instead. Since `dev-digital` comes before `digitalproductlifecycle` (alphabetically), it is higher on the list. HAProxy, on the other hand, evaluates ACLs top-down and uses the first one that matches the request. You can change the ordering by specifying `aclName`. For example, if you set `dev-digital` to `digitalx`, it should be placed after `digitalproductlifecycle`.

I'm open to a suggestion how we can improve the ordering.

**Comment by lhenry7** [comment]
Yes, I see that now in the docs. I don't have any good suggestions on how to change, but as long as there is a way to handle it I think it is fine. Thanks

**Comment by lhenry7** [comment]
Sorry to belabor  this, but now I'm confused by this test. Here I have the same situation where the serviceName order should cause the same problem, but it works just fine:

frontend services
    bind *:80
    bind *:443
    mode http

    acl url_nginx-test123_app80 path_beg /digitalproductlifecycle
    acl srcPort_nginx-test123_app80 dst_port 80
    acl url_nginx-test123_app443 path_beg /digitalproductlifecycle
    acl srcPort_nginx-test123_app443 dst_port 443
    acl domain_nginx-test123_app hdr(host) -i my.test.com
    use_backend nginx-test123_app-be80 if url_nginx-test123_app80 domain_nginx-test123_app srcPort_nginx-test123_app80
    use_backend nginx-test123_app-be443 if url_nginx-test123_app443 domain_nginx-test123_app srcPort_nginx-test123_app443
    acl url_nginx-test_app80 path_beg /digital
    acl srcPort_nginx-test_app80 dst_port 80
    acl url_nginx-test_app443 path_beg /digital
    acl srcPort_nginx-test_app443 dst_port 443
    acl domain_nginx-test_app hdr(host) -i my.test.com
    use_backend nginx-test_app-be80 if url_nginx-test_app80 domain_nginx-test_app srcPort_nginx-test_app80
    use_backend nginx-test_app-be443 if url_nginx-test_app443 domain_nginx-test_app srcPort_nginx-test_app443

nginx-test_app should be before nginx-test123_app, right? But it properly put the servicePath /digitalproductlifecycle before /digital.

**Comment by lhenry7** [comment]
Also, here in my full config, the service names are clearly not in alpha order all the way through. Is there some threshold where services over a certain number or ACL's over a certain number is causing issues? Currently several domains are being directed to the wrong service backends, so not only the order is messed up, the the acl's themselves seem to be confused.


[haproxy.cfg.txt](https://github.com/vfarcic/docker-flow-proxy/files/1160220/haproxy.cfg.txt)

**Comment by lhenry7** [comment]
Here are the yml files for one of the miss-sorted services examples.
[miss-sorted-stacks.zip](https://github.com/vfarcic/docker-flow-proxy/files/1160301/miss-sorted-stacks.zip)

 Also, in that haproxy.cfg, the requests that match the acl's:
    acl url_stage-genewsroom_varnish80 path_beg /
    acl srcPort_stage-genewsroom_varnish80 dst_port 80
    acl url_stage-genewsroom_varnish443 path_beg /
    acl srcPort_stage-genewsroom_varnish443 dst_port 443
    acl domain_stage-genewsroom_varnish hdr(host) -i stage.genewsroom.com
    use_backend stage-genewsroom_varnish-be80 if url_stage-genewsroom_varnish80 domain_stage-genewsroom_varnish srcPort_stage-genewsroom_varnish80

end up going to the backend that matches these acl's(both 80 and 443):
    acl url_stage-mygestory_app80 path_beg /
    acl srcPort_stage-mygestory_app80 dst_port 80
    acl url_stage-mygestory_app443 path_beg /
    acl srcPort_stage-mygestory_app443 dst_port 443
    acl domain_stage-mygestory_app hdr(host) -i stage.mygestory.com
    use_backend stage-mygestory_app-be80 if url_stage-mygestory_app80 domain_stage-mygestory_app srcPort_stage-mygestory_app80
    use_backend stage-mygestory_app-be443 if url_stage-mygestory_app443 domain_stage-mygestory_app srcPort_stage-mygestory_app443

**Comment by vfarcic** [comment]
The problem is that the rule about ordering does not apply to services with path set to `/`. That is (probably) correct since they are catchAll type of service and should be at the bottom. The real problem is that services with the path `/` should be at the bottom only if there is no domain set. I pushed the fix and a new tag is available. Can you please try it out and let me know how it went?

**Comment by lhenry7** [comment]
Thanks, what is the tag for this fix?

Larry Henry
Staff Infrastructure Architect - Digital Strategy Group   GE Digital

T 734 641 2415
F 734 727 5420
M 734 502 9855
Larry.Henry@ge.com<mailto:Larry.Henry@ge.com>

Grace Lake Corporate Center
One Village Center Drive
Van Buren Twp, Michigan 48111
General Electric Company

GE imagination at work

**Comment by vfarcic** [comment]
My bad... The push fixes a different issue. I'll work on a fix for this one during the weekend.

**Comment by vfarcic** [comment]
@lhenry7 Can you please try the release 17.07.22-2?

**Comment by lhenry7** [comment]
I have a reproducible set of stacks, where multiple deployments make proxy go horribly wrong. I have a set of 3 manager nodes and 2 worker nodes in the swarm cluster.
Along with the stacks in the attached zip file, is a script I use to stop an start service stacks. So for instance, to start the proxy-stack.yml, I use './deploy_stack proxy'. So basically any stack name without the -stack.yml part.
 If I run './deploy_stack  nginx-digitalprod nginx-digital nginx-test123 nginx-test' a few times (usually just once or twice), the 2 flow-proxy instances are either missing service acl's or backends, and usually don't even match each other. Another thing you can try after getting some service defined in proxy is 'docker service update --force nginx-test123_app', (or either of the 4 services) this will usually cause the 2 proxy instances to regenerate different haproxy.cfg files as well.
[flow-proxy-stacks.zip](https://github.com/vfarcic/docker-flow-proxy/files/1173838/flow-proxy-stacks.zip)

**Comment by vfarcic** [comment]
I think that the problem with that script is that it can generate race conditions. Things might be happening too fast for the proxy with removal and creation of the same services in only a couple of seconds. I did not foresee that scenario since normally you would not do that.

From the deployment point of view, if you remove `docker stack rm $stack`, the effect would be the same. It is preferable to update the stack than to remove it and create it again.

I assume you have a good reason for removing the service. Can you double check whether DFP behaves the same if `sleep` is longer (let's say 10 seconds)? If that (temporarily) fixes the problem, the solution would be to change DFLE `DF_INTERVAL` to `1` second instead of the default of `5`. You need to give DFLE enough time to detect that a service is removed, announce it to DFP, than create the new service, and, again, add it to DFP.

I'd start by revisiting your process and checking whether it makes sense to remove the stack. If that is mandatory, change the `sleep` to a longer interval and, depending on the result, we'll think of the next steps. Does that sounds like a plan?

**Comment by lhenry7** [comment]
Yes, the script was just there to help easily cause the issue. I think the real life use case is I have over 100 services running, with a CI process that can start/upudate services at any time. Occasionally they can happen together too quickly for the proxy to get the cfg built completely and correctly. Also, if the replica is just 1, the replacement service will likely have a new IP, so I wonder when the new IP will get resolved by the proxy? I'm interested in your thoughts around changing the DF_INTERVAL though. Do you think making it longer or shorter would help give it time to act on 1 event before starting work on another? Will the events queue up nicely for it while it was working? You mentioned shortening it to 1, but would increasing it to say 15-20 mean it would have more time to work on an event, or does it try and process multiple events at a time?

**Comment by vfarcic** [comment]
> I think the real life use case is I have over 100 services running, with a CI process that can start/upudate services at any time.

Starting and updating services should not be the problem. The issue is if a service is removed and created with the same name within a short period. Normally, there should be no need for that since `docker stack deploy` alone should put the services in the correct state.

> Occasionally they can happen together too quickly for the proxy to get the cfg built completely and correctly.

That is the problem since DFLE is designed to send information periodically. Did you try decreasing `DF_INTERVAL` to `1`? If that does not help, we can disable DFLE from sending requests to DFP and add a [reload](http://proxy.dockerflow.com/usage/#reload) request to your scripts. Instead of waiting for DFLE, you'd reconfigure DFP every time you deploy something. Do you think that would be an option?

> Also, if the replica is just 1, the replacement service will likely have a new IP, so I wonder when the new IP will get resolved by the proxy?

DFP does not use IPs. It forwards requests to service name and lets Docker networking handle LB to one of the replicas.

> I'm interested in your thoughts around changing the DF_INTERVAL though. Do you think making it longer or shorter would help give it time to act on 1 event before starting work on another?

I'm not sure since I did not try such a scenario. My CD pipelines always create new services or update existing ones. They never remove and immediately create the same one. My best case would be to reduce it to `1`. If that does not work (and you keep the same process of removing/creating the same service), I'd go with the suggestion to disable DFLE from sending requests to DFP and use the reload request I mentioned earlier.

> Will the events queue up nicely for it while it was working? You mentioned shortening it to 1, but would increasing it to say 15-20 mean it would have more time to work on an event, or does it try and process multiple events at a time?

I think that it might get confused since it would find both remove and create events in Docker API. Instead, I'd increase sleep time in your scripts. Put it to 15-20 and it should work like a charm.


Suggestions in order of what I'd try first:

1. Do not remove/create services, execute `docker stack deploy` or `docker service update` instead. It is the process recommended with or without DFP.
2. Increase sleep time between remove and create commands.
3. Disable DFLE from sending requests to DFP. Use DFP reload request instead.
4. Decrease `DF_INTERVAL`.

Do not try all those suggestions at once. Choose one of them (preferably those higher on the list) and try it out.

Please let me know how it went.

**Comment by lhenry7** [comment]
Hi,

> DFP does not use IPs. It forwards requests to service name and lets Docker networking handle LB to one of the replicas.

I know you use service name, but even that resolves to a VIP. Can there be  case where a service update causes a new VIP to be used, and haproxy is still using the old VIP it resolved when the haproxy.cfg was first built? That could explain why I've occasionally seen "could not resolve address" errors in logs. The way to make haproxy re-resolve server IP's requires healthchecks on the servers, which you don't do.

> 1. Do not remove/create services, execute docker stack deploy or docker service update instead. It is the process recommended with or without DFP.
> 2. Increase sleep time between remove and create commands.

 These are just relics of the script created only to make the problem immediately apparent. The normal process is to do service updates. I can easily increase the timeout to 10s and the script will work. There are times when stopping/starting is needed though, for instance 'docker service update' doesn't cause the image to be checked and re-fetched from the repository if tag=latest has been updated.

I will try changing the DF_INTERVAL to 1 and see how that works.

**Comment by vfarcic** [comment]
> I know you use service name, but even that resolves to a VIP. Can there be case where a service update causes a new VIP to be used, and haproxy is still using the old VIP it resolved when the haproxy.cfg was first built?

VIP is the same for a service no matter how often you update it. Even if it changes, it should not matter because it is not resolved by DFP, but by Docker Overlay network. In other words, the name of the service is constand and networking resolves is and forwards it to one of the replicas.

> That could explain why I've occasionally seen "could not resolve address" errors in logs. The way to make haproxy re-resolve server IP's requires healthchecks on the servers, which you don't do.

There is no such thing (as far as I know) as health checks on the servers since everything is happening inside Docker networking. What there is, indeed, are health checks as part of Dockerfile. If there is none, Overlay will send a request to any of the replicas that are running. On the other hand, if you do set `HEALTHCHECK` as part of your Dockerfile, Overlay will send requests only to replicas that passed the check which is executed periodically. `HEALTHCHECK` should be mandatory for every service no matter whether you use DFP or anything else.

> There are times when stopping/starting is needed though, for instance 'docker service update' doesn't cause the image to be checked and re-fetched from the repository if tag=latest has been updated.

`docker service update --image ...` does check whether there is new latest and if there is it will update the service. Even though that does work, it is a very bad practice. How do you know which version is running? Even if you do through image hashes, you will not be able to use features like `docker service update --rollback`. There are quite a few other features that benefit from knowing which version is running. Since you are already using some CD tool for deployment, there should be no obstacle for using specific versions and benefits are obvious.

**Comment by lhenry7** [comment]
Ok, sorry for the long diversion... but back to the original issue. Attached are flow-proxy stack and 2 nginx stacks. The sort order is still not what I expect. the service names are nginx-test_app and nginx-test123_app.
Expected:
nginx-test_app ACL's would appear in the haproxy.cfg before nginx-test123_app ACL's

Observed:
nginx-test123_app ACL's are before nginx-test123_app ACL's
[proxy-nginx.zip](https://github.com/vfarcic/docker-flow-proxy/files/1194419/proxy-nginx.zip)

**Comment by vfarcic** [comment]
When ordered alphabetically (as least through Go code) `_` is before numbers. I don't think that changing default algorithm for sorting would be worthwhile. Would you be OK knowing that `_` goes before numbers? That should let you rename services accordingly or use `aclName` instead. What do you think?

**Comment by lhenry7** [comment]
Yes, agreed. As long as it is logical and explainable thing, it is fine. So it’s using POSIX sort ordering, not UTF-8. I think UTF-8 would sort underscore after numbers.
