### ISSUE TITLE
DFP should ignore services that cannot be added to the configuration

### ISSUE THREAD

**Issue by valeriomazzeo** [vfarcic/docker-flow-proxy#310]
Currently this causes docker-flow-proxy to restart infinitely resulting in other (properly configured) services to be unavailable.

**Comment by vfarcic** [comment]
@valeriomazzeo Can you come up with a set of test commands that would prove that it currently fails and, more importantly, will prove that the fix works?

**Comment by valeriomazzeo** [comment]
The most common error I have seen is that if you configure in the proxy a service for a container that doesn't exist, it keeps failing because it can't connect to it.

Another common one, is some misspell in one of the services configuration, like an invalid log format.

**Comment by vfarcic** [comment]
The problem is that it is hard (if not impossible) to distinguish services that are created but not yet running from those that will never run. Swarm Listener retries attempt to reconfigure the proxy hoping that the service will become available. It uses env. var. `DF_RETRY`(defaults to `50`) and `DF_RETRY_INTERVAL` (defaults to 5). With the default config, it will continue sending reconfigure requests for 250 seconds (50 x 5) and give up after that.

What I wondering is:
1. Whether the retry logic is failing and DFP continues receiving reconfigure requests even after 250 seconds?
2. Whether there might be a better logic we can employ.

Can you confirm 1) and let me know if you have any suggestion for 2)?

**Comment by valeriomazzeo** [comment]
```
[ALERT] 218/104245 (42) : parsing [/cfg/haproxy.cfg:64] : 'server mycontainer-host' : could not resolve address 'mycontainer-host'.
[ALERT] 218/104245 (42) : Failed to initialize server(s) addr.
```

1. I think the retry logic works, although it is extremely heavy when deploying a new stack when all the services are trying to start at the same time. In that scenario the proxy just keeps restarting. In case something will never be available at some point I think df-proxy gives up resulting in **all** of the services being unavailable for the end user.

2. I am not sure, as a "dumb" df-proxy user I would expect to see the proxy up and running even with the wrong configuration. Then, if it gets a request that can be routed, is all good, otherwise it returns a 503.

I am not sure I understand the technical details of why the proxy has to be reconfigured continuously.

**Comment by vfarcic** [comment]
Fix is available from the tag `vfarcic/docker-flow-proxy:17.08.10-24`. From now on, if a service prevents DFP from configuring, it will be removed and another attempt to reconfigure will be executed (this time without the problematic service). Can you please try it out and let me know whether it fixed your problem?

**Comment by valeriomazzeo** [comment]
Thanks!

> ... and another attempt to reconfigure will be executed (this time without the problematic service).

Does this handle only the bad configuration case, or also when the service is not available (for example: still booting)?

Will try it first thing tomorrow.

**Comment by vfarcic** [comment]
The flow is:

1. DFSL sends a notification to DFP
2. DFP reconfigures itself using the info about the new service. The rest is not executed if that works.
3. DFP fails to configure HAProxy (service is still not available, labels are wrong, and so on). It does not know whether the problem is temporary (service not yet running) or permanent.
4. DFP reverts to the configuration without the new service and responds to DFSL that there's something wrong.
5. DFSL receives the error from DFP and retries the same requests after a pause (by default 5 seconds) or, if all attempts to configure DFP failed (by default 50), it gives up and stops sending reconfigure requests to DP.

**Comment by valeriomazzeo** [comment]
Clear, I have only one question about 5.

When DFSL sends the retry request, is DF capable of validating and load the new configuration without going down?

In other words, is DF going to go down every 5 seconds for 50 times if something goes wrong, or during that period of time will it still be able to serve the other services?

**Comment by vfarcic** [comment]
It will not go down in those cases. At least, that's the intention from the start and, hopefully, it is now fixed. Please let me know if that's not the case.
