### ISSUE TITLE
Switching between services without using the remove option 

### ISSUE THREAD

**Issue by ozlerhakan** [vfarcic/docker-flow-proxy#313]
Hi,

Thank you for such a good project! When I tried a blue-green deployment using docker-flow-proxy, I have realised that I couldn't have changed services among them all of which exist and run in my swarm cluster. 

My first request is just to use the blue service:

```
$ curl "http://ip:8080/v1/docker-flow-proxy/reconfigure?serviceName=blue_world&serviceDomain=/&port=3030"
``` 

In another terminal, I see that everything works good:

```
... 
 world 855ca3254640
 world 98f144ec2fe3
 world 855ca3254640
 world 98f144ec2fe3
 world 855ca3254640
...
```

Let's now switch the service from the blue to the green:
```
$ curl "http://ip:8080/v1/docker-flow-proxy/reconfigure?serviceName=green_world&serviceDomain=/&port=3030"
``` 

Again in the terminal, the changes effect the output ( starting `WORLD` as uppercase ) as I expect, 

```
... 
 world 855ca3254640
 world 98f144ec2fe3
 WORLD ea7dc2d722e9 
 WORLD 98148ee8a193 
 WORLD ea7dc2d722e9 
...
```

When I decide to see the service green instead the blue one, I couldn't see any differences in the output:

 ```
$ curl "http://ip:8080/v1/docker-flow-proxy/reconfigure?serviceName=blue_world&serviceDomain=/&port=3030"
``` 

```
... 
 WORLD ea7dc2d722e9 
 WORLD 98148ee8a193 
 WORLD ea7dc2d722e9 
 WORLD 98148ee8a193 
 WORLD ea7dc2d722e9 
...
```

Do I need to add additional options to make this possible? BTW, this deployment works well when removing the blue service from the Docker Flow Proxy after changing the state to the green service.

**Comment by vfarcic** [comment]
Proxy ACLs are ordered alphabetically. When a request is sent to the proxy, it forwards it to the first one that is a match. What that means is that when there are two or more services with the same match (e.g. `servicePath=/`), requests will be forwarded to the first one on the list. So, if you configure `blue_world` and `green_world`, all requests will be forwarded to `blue_world` because it comes alphabetically before `green_world`. You can provide parameter `aclName` if you want to change the order of services. So, if you'd like requests to be forwarded to `green_world`, you can set `aclName` to `1_green_world` or anything else that would be ordered before `blue_world`.

The BG process could be something like:

First release:

```
curl "http://ip:8080/v1/docker-flow-proxy/reconfigure?serviceName=blue_world&servicePath=/my-service&port=3030"
```

At this moment there is only `blue_world` configured so all requests with the path that starts with `/my-service` should be sent there.

Please note that I changed `serviceDomain` to `servicePath` since `/` is not a domain. I also added a path that uniquely identifies a service (e.g. `/my-service`). If you use `/` as path without a domain, you will not be able to have multiple services configured since all requests starting with `/` would be sent to a single service. If your service cannot be configured to use a custom path, you can add `reqPathSearch` and `reqPathReplace` params.

```
curl "http://ip:8080/v1/docker-flow-proxy/reconfigure?serviceName=green_world&servicePath=/my-test-service&port=3030"
```

Now the second release is configured as well. The first release will continue serving requests to `/my-service` and your users will not be affected. At the same time, you can test the new release by sending requests to `/my-test-service`. Once the new release is tested and works as expected, you can change the path and remove the old service.

Testing is the crucial part. Without it, I don't think there is a reason to use BG instead rolling updates.

```
curl "http://ip:8080/v1/docker-flow-proxy/reconfigure?serviceName=green_world&servicePath=/my-service&port=3030"

curl "http://ip:8080/v1/docker-flow-proxy/serviceName?serviceName=blue_world"
```

The first command changed the path of the new release to be the same as the old release and the second removed the old release.

Please note that I haven't tested this process myself. I switched to rolling updates completely and do not use BG since I started using Swarm Mode (new Swarm). The process I described is probably (more or less) correct. Please try it out and let me know whether it works.

As a side question, I'd be interested to know why you choose BG instead rolling updates. Later comes out of the box with Swarm Mode and is, generally, a preferable way to deploy new releases. I'm sure you have a good reason for choosing BG and it would be interesting for me to understand your use-case.

**Comment by ozlerhakan** [comment]
Thank you @vfarcic for the comprehensive details. 

I have tested your instructions:
```
$curl "http://ip:8080/v1/docker-flow-proxy/reconfigure?serviceName=green_world&servicePath=/my-service&port=3030"

$curl "http://ip:8080/v1/docker-flow-proxy/remove?serviceName=blue_world"
```

However, I have receive 1 second downtime.

```
$ while [ true ]; do curl http:/swarm-master-ip/world; echo; sleep 1; done;
...
 world 71d2f1e2b5ae blue
 world 4378ee16f3fe blue
curl: (56) Recv failure: Connection reset by peer

 WORLD 98148ee8a193 green
 WORLD ea7dc2d722e9 green
 WORLD 98148ee8a193 green
...
```

If I add your mentioned flag `aclName` and remove the blue service afterwards, I have zero downtime.

```
$ curl "http://gox.kitapp.org:8080/v1/docker-flow-proxy/reconfigure?serviceName=green_world&aclName=1_green_world&servicePath=/&port=3030"

$ curl "http://ip:8080/v1/docker-flow-proxy/remove?serviceName=blue_world"
```

```
...
 world 4378ee16f3fe blue
 world 71d2f1e2b5ae blue
 world 4378ee16f3fe blue
 WORLD 98148ee8a193 green
 WORLD ea7dc2d722e9 green
 WORLD 98148ee8a193 green
...
```

> As a side question, I'd be interested to know why you choose BG instead rolling updates. Later comes out of the box with Swarm Mode and is, generally, a preferable way to deploy new releases. I'm sure you have a good reason for choosing BG and it would be interesting for me to understand your use-case.

I have tested the `docker config` approach with one nginx proxy  service + 2 instance of the 2 different services (like the Blue and Green service concept). Creating a new docker config file  and updating the nginx service with that file gives me 2 seconds downtime in my swarm cluster. 

```
$ docker service update \
    --config-rm service-nginx-world-blue \
    --update-order start-first \
    --config-add source=service-nginx-world-green,target=etc/nginx/conf.d/default.conf \
    nginx
```
Next to this, while querying a get request every minute again, If I just update my service's image with the new release like below, I receive one second downtime.
Here is my stack file of myservice:

```
...
  world:
    image: app:green
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - proxy
    stop_grace_period: 20s
...
```

```
$ docker service update \
    --update-order start-first \
    --image app:blue \
    myservice_world
```

**Comment by vfarcic** [comment]
My guess is that you have downtime because the process inside a container needs some time to start. Did you define HEALTHCHECK? If you did, Docker would wait until it received `0` from it before it starts sending traffic to it and moving onto a next replica.

**Comment by ozlerhakan** [comment]
> Did you define HEALTHCHECK? If you did, Docker would wait until it received 0 from it before it starts sending traffic to it and moving onto a next replica.

Ah no I haven't configured a HEALTHCHECK option.

**Comment by ozlerhakan** [comment]
After including a HEALTHCHECK into my service, I have zero downtime with no need an extra service. Thank you @vfarcic ! 

Nevertheless  It's also good to test docker-flow-proxy for that purpose :)

**Comment by vfarcic** [comment]
I'll close this issue. Feel free to reopen it if you feel there's still something missing.
