### ISSUE TITLE
failover on node reboot

### ISSUE THREAD

**Issue by sstubbs** [vfarcic/docker-flow-proxy#322]
I am currently running a cluster of 3 core os nodes. When they automatically update and reboot the proxy does not retain the previous setup routes. I have tried running two instances but then requests to the rebooted nodes container still fail.

I have read an old issue about this https://github.com/vfarcic/docker-flow-proxy/issues/12 which suggests mounting the /cfg/ folder on the host. Is this still the best way or is there a better way now?

**Comment by sstubbs** [comment]
I am using the docker swarm setup http://proxy.dockerflow.com/swarm-mode-auto/

**Comment by vfarcic** [comment]
Mounting `/cfg` is not a good option any more. The proxy now gets all the information it needs from *Swarm Listener*.

When a replica of the proxy is created it sends a request to *Swarm Listener* which returns all the services the proxy needs to configure itself. So, as long as *Swarm Listener* is running, the proxy should get all the information it needs. If a node with the proxy is restarted Swarm will schedule proxy replica on a different node which will get all the info from the *Swarm Listener*. 

I'm a bit surprised that did not happen in your case. Can you please post more info about the update? You're updating one node at a time (not all at once)? Would it be possible to replicate your situation locally with, for example, CoreOS running with Vagrant/VirtualBox? Can you post the logs of the proxy and Swarm Listener replicas?

**Comment by ChaosMTA** [comment]
@vfarcic would this still be the case if the node that was restarted was the one running Swarm Listener?

**Comment by vfarcic** [comment]
@ChaosMTA If the Swarm Listener (DFSL) fails Docker Swarm will reschedule it on a healthy manager node. When it starts (again), the first thing DFSL does is get all the info about the services from one of the managers and resends all the info to DFP. That way no data is lost and DFP is up-to-date even if for a short period DFSL was down (usually not longer than a second since it is very small to pull and fast to boot).

Does this answer your question @ChaosMTA?

**Comment by ChaosMTA** [comment]
Yep that answers my question! Thanks for the detailed information, appreciated @vfarcic
