### ISSUE TITLE
[NFR] Support IPv6

### ISSUE THREAD

**Issue by ruudboon** [vfarcic/docker-flow-proxy#354]
Would it be possible to have the proxy listen to incoming request over IPv6 and forward it to the services? 
The connection to the service could still be IPv4 if you ask me.

**Comment by basz** [comment]
This seems to be the problem I was having on a domain that listens on both ipv4 and ipv6. The lets encrypt companion could never validate the challenge because it (certbot) apparently now prefers to use ipv6 over ipv4.

After I deleted the AAAA record for the domain as was well again.

https://community.letsencrypt.org/t/certbot-renewal-issue-with-ipv6-address-and-web-server-configuration/34730/4

Seems to me this should be possible eventually anyways, but I know nothing of ha_proxy. Perhaps this will help: https://www.internetsociety.org/resources/deploy360/2013/making-content-available-over-ipv6/

**Comment by ruudboon** [comment]
Experienced the same issues with letsencrypt.

**Comment by vfarcic** [comment]
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.
