### ISSUE TITLE
Multiple proxy nodes possible?

### ISSUE THREAD

**Issue by yanky83** [vfarcic/docker-flow-proxy#38]
Hello,

is it possible to deploy mutliple clustered proxy nodes as docker services?

Maybe Im too blind to see :)

Thanks.

**Comment by vfarcic** [comment]
Did you check **The Swarm Mode** link in the [README#modes](https://github.com/vfarcic/docker-flow-proxy#modes)? It contains [Scaling the Proxy](https://github.com/vfarcic/docker-flow-proxy/blob/master/articles/swarm-mode.md#scaling-the-proxy) section that explains how to scale it.

Please let me know whether that helped. There's always a chance that I misunderstood your question/problem.

**Comment by yanky83** [comment]
Perfect, sry for my blindness. 

One more question though: how would multiple proxies handle session stickiness for example?

**Comment by vfarcic** [comment]
If you need a proxy that uses sticky sessions, *Docker Flow: Proxy* might not be a solution for you. To be more precise, the problem lies in the new Swarm networking. Load balancing is now done by Swarm network and there is no guarantee that requests originating from the same source will be sent to the same instance. You will probably need to fall back to the "old" networking model. That would mean that you'd need to monitor Docker instances and update proxy config with the IP/port of a container whenever a new one is created or an existing one is destroyed.

You should evaluate pros and cons of not leveraging new networking features against the effort to move sessions outside.

P.S. I'm always trying to make my services stateless so I don't have the problem with sticky sessions. When I do need a session, it is stored outside a service (e.g. Redis). However, I am aware that not everyone has the luxury to start from scratch or redesign a service.

**Comment by vfarcic** [comment]
Closing the issue due to inactivity.
