### ISSUE TITLE
Feature Request - Remove config entry when service is removed

### ISSUE THREAD

**Issue by goffinf** [vfarcic/docker-flow-proxy#51]
To provide consistency of behaviour of the 'remove' action to 'reconfigure' I request that if a docker service is removed (docker service rm myservice) then the corresponding entry in haproxy.cfg should also be removed.

See linked issue  https://github.com/vfarcic/docker-flow-proxy/issues/50

**Comment by vfarcic** [comment]
The current idea is to keep Swarm monitoring separate from the proxy. If the proxy runs alone, users are required to send reconfigure and remove requests. If it is combined with the [Docker Flow: Swarm Listerner](https://github.com/vfarcic/docker-flow-swarm-listener) project, reconfigure and remove requests will be sent by the listener.

The reason for such separation lies in the future plans of the listener. I'll extend it to perform other types of actions unrelated to the proxy (actually, it already does but is not documented). The second reason is that the listener needs to run on one of the nodes that are configured to be Swarm manager (it uses its socket to query engine's API). If that would be merged into the proxy, it would have the same restriction. By keeping it separate, proxy can run on any node (manager or worker).

Pending action is to provide an example of using the proxy together with the listener in proxy's README. Until then, the is an example in the README of the listener.

Please close this ticket if proxy/listener combination fits your needs. Otherwise, we can brainstorm a different solution.

**Comment by goffinf** [comment]
It does. Closing.
