### ISSUE TITLE
Feature Request - List proxy entries

### ISSUE THREAD

**Issue by goffinf** [vfarcic/docker-flow-proxy#52]
Currently in order to confirm what entries exist it appears that it is necessary to find where the docker-flow-proxy container is running then examine the haproxy.cfg file in that container.

I request an additional API method (perhaps 'list') that will return ...
1. A full list of existing entries
2. Allow filtering of the returned list based on a regex of serviceName

**Comment by vfarcic** [comment]
I made a preliminary POC that returns HAProxy configuration.

Please run the proxy 1.91+ or later and send a request to `[PROXY_IP]:[PROXY_PORT]/v1/docker-flow-proxy/config`.

Do you think that would match your needs?

Making it as a JSON list would be more complicated since the proxy does not keep in memory (or anywhere else) the parameters sent through reconfigure requests. That information can be obtained through Consul or [Docker Flow: Swarm Listener](https://github.com/vfarcic/docker-flow-swarm-listener). Before I start working on an API that would return entries stored in Consul and Docker Engine's API (through the Swarm Listener), I'd like to confirm that the current solution (`/v1/docker-flow-proxy/config`) is not enough.

In any case, even if existing entries are returned in JSON format, I think that seeing HAProxy config is a useful addition.

**Comment by vfarcic** [comment]
I'll close this ticket assuming that the new `/config` API provides what is needed. If that's not the case, please reopen the ticket.
