### ISSUE TITLE
Automatic LetsEncrypt support

### ISSUE THREAD

**Issue by no-more** [vfarcic/docker-flow-proxy#56]
Hi,

This was asked once in #28 but hidden between other request.

It would be great to have an automatic letsencrypt subscription and renewal process included into this great docker image.

A shared volume might be required in order to share the cert between nodes and instances.

Do you think this is possible ?

Thanks.

**Comment by vfarcic** [comment]
I still did not manage to incorporate Let's Encrypt service to the proxy but I did make a progress in that direction.

I just added a way to put a certificate to a running proxy service. You can find the information about the request endpoint and parameters in the [Put Certificate](https://github.com/vfarcic/docker-flow-proxy#put-certificate) section.  A tutorial can be found in the [Configuring Service SSLs And Proxying HTTPS Requests](https://github.com/vfarcic/docker-flow-proxy/blob/master/articles/swarm-mode-listener.md#configuring-service-ssls-and-proxying-https-requests) section of the [Swarm Mode (Docker 1.12+) With Automatic Configuration](https://github.com/vfarcic/docker-flow-proxy/blob/master/articles/swarm-mode-listener.md) article.

There is no need for shared volumes. It is enough to add a certificate to one and it will propagate the change to all other replicas. On the other hand, if a new replica is added, it will sync with those created before it and fetch, among other things, all the certificates. In other words, by communicating with each others, proxy replicas are always synced.

Please note that this is only an intermediary step. It'll allow you to add certificates to the proxy. The part with Let's Encrypt subscription and renewal process is still pending. I need to think how to do it in an elegant way.

**Comment by no-more** [comment]
Hi,

Thanks a lot, I'm still in early stage of my project, and won't be able to test this soon, but that's a great news.

**Comment by hamburml** [comment]
Any news on this?
Afaik the haproxy would need a rule for the letsencrypt/acme certificate requests so that the certificates could be renewed without any downtimes.

I found this blogpost which describes the changes needed to haproxy https://daplie.com/articles/lets-encrypt-with-haproxy/ but I don't know if there were any changes between hyproxy 1.5 and 1.6 (or 1.7, depends on how current the local docker-flow-proxy image is).

I also found this plugin which could be useful for that task https://github.com/janeczku/haproxy-acme-validation-plugin.

**Comment by vfarcic** [comment]
The project became relatively popular and I am swarmed with requests. The bad news is that there are still very few contributors and I cannot manage to close the issues fast enough. To make things more complicated, this request has a relatively low priority since there is already a way to upload a certificate.

Can you help out? Any contribution towards this feature would be greatly appreciated.

**Comment by mckabo** [comment]
I think it would be beneficial to put the renewal/creation stuff into the listener (a bit like this: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion). But instead of using the shared volume we can use the proxy api.

**Comment by vfarcic** [comment]
That's a very good idea. Would you like to help @mckabo ?


Adding @hamburml since he already started working on this feature.

**Comment by mckabo** [comment]
yes of course!

**Comment by vfarcic** [comment]
@mckabo Great. Please let me know if you need any info or help.

**Comment by hamburml** [comment]
@mckabo We could use the proxy-api to add the certificate, that is true. But I think we should also give the ability to extract (shared volume? mounted volume with the docker host?) the certificate because letsencrypt has a limit on how often a certificate can be created for a given domain in a certain time period. When this limit is reached no certificates can be created anymore and the time period needs to end.

**Comment by vfarcic** [comment]
The proxy already has a request for uploading certificates (https://github.com/vfarcic/docker-flow-proxy#put-certificate). If that request contains the `distribute=true` parameter, the certificate will be propagated to all proxy instances. Hence, no need for a shared volume.

The listener can be scheduled to renew the certificate once a week. Frequency can be adjusted through an environment variable.

I'm not very familiar with Let's Encrypt so I might have misunderstood how it works. If that's the case, please ignore this comment.

**Comment by hamburml** [comment]
@vfarcic https://letsencrypt.org/docs/rate-limits/ I just meant this limit. The proxy-upload-api with distribute=true is cool and should be used, yes. But when someone is testing docker-flow-proxy and swarm-listener and creates the certificate via the swarm-listener very often he won't get a certificate again for a certain time. I only want to ensure that the user can extract his certificate.

**Comment by vfarcic** [comment]
@hamburml You're right. 20 certificates per week can be spent in no time through tests. We'll think of a way to avoid that. Mocks?

**Comment by mckabo** [comment]
I had similar concerns (but honestly not about this limit; I wasn't aware of this limit) regarding failing, scaling, moving... of the listener.

**Comment by vfarcic** [comment]
I don't think that there is a reason to scale the listener. If it fails, Swarm will reschedule it and a few moments later it will run again. During that brief period, no service would be affected. Also, it is designed in a way that it would recuperate all services upon rescheduling. As long as we keep the listener stateless, we should not have any problem. After all, it is only a bridge between Swarm (and soon Let's Encrypt) and other services (at the moment only proxy).

**Comment by mckabo** [comment]
Regarding the testing purposes we might can utilize the Let's Encrypt staging env (https://letsencrypt.org/docs/staging-environment/).

**Comment by mckabo** [comment]
Here are some resources which may can be utilized:
- https://github.com/janeczku/haproxy-acme-validation-plugin (maybe the lua script can be utilized to be triggered by the proxy api)
- (https://github.com/leandromoreira/tls_certificate_generation)
- (https://github.com/rekby/lets-proxy)

**Comment by hamburml** [comment]
Hi!

FYI, I created an addition to Docker Flow which allows the automatic creation and renewal of Let's Encrypt certificates and is called Docker Flow: Let's Encrypt. You can find it here https://github.com/hamburml/docker-flow-letsencrypt and https://hub.docker.com/r/hamburml/docker-flow-letsencrypt/. It's fairly big with 204 MB but currently there are no official certbot images uploaded on docker hub. They are working on this and when they provide them I will update the docker image and hopefully it will be a lot smaller

Default behavior is that Let's Encrypt certificates are tried renewed two times a day (03:00 and 15:00 UTC) and send to the Docker Flow: Proxy instance. You can change this behavior via nvironment variables.

This is my first public repository so please bear with me when something isn't working.
PS: Backup your /etc/letsencrypt folder!

Thanks to vfarcic for his help 👍

If you have questions or problems pls open an issue :)

**Comment by vfarcic** [comment]
Is there some prerequisite (authorization?) before we run the container?

**Comment by hamburml** [comment]
The container must be part of the same network as the proxy and the docker host needs an /etc/letsencrypt folder. I would also advice to start the container always on the same docker host (so he can ceach the /etc/letsencrypt folder on the host which holds the certs).

**Comment by vfarcic** [comment]
What would happen if there is no volume? Certs would be stored in a container and it would work as expected? If that's the case, I think that the major question is what would happen if that container fails and Swarm reschedules it somewhere else. Would the service request a new certificate(s) and continue as if nothing happened or...?

**Comment by hamburml** [comment]
The swarm can't reschedule it somewhere else when `--constraint 'node.id==<nodeId>` was set. When this constraint is not set it will be started somewhere else and can't find the certificates. It is not a named volume. When the folder does not exist the container will not start.

**Comment by vfarcic** [comment]
I think that's great :)

I'm just trying to brainstorm possible improvements. If that node fails, there will be no certificates and the whole system (at least https parts of it) might fail as well due to expired certificates.

Would it be possible to store certs inside a container without exposing them as a volume. If a service is rescheduled, it would request them again from Let's Encrypt.

**Comment by hamburml** [comment]
Yeah, when the node totally fails (like hardware failure) the certs are almost gone (docker flow: proxy still has a copy but the config files and generated files from certbot are gone). Would be best if the /etc/letsencrypt folder could be backed up.

**Comment by raarts** [comment]
How about putting letsencrypt into the listener (as earlier suggested) and automatically create a backend for it on the proxy, and give each domein a path `/.well-known/acme-challenge` which points to that backend, so letsencrypt.com is able to retrieve the challenge url.

I would leave it up to the user on how and where to mount the /etc/letsencrypt folder, it's just a volume. They can do a host-mount, or a named volume to keep it safe across re-deploys.

**Comment by vfarcic** [comment]
@hamburml What do you think? If you feel that's a good idea, I can help transferring your code to the listener.

**Comment by hamburml** [comment]
@vfarcic Hm... I don't know if that is really necessary (or makes stuff even worse in the future when thinking about updating the swarm-listener).

The whole point was to have the ability of just "plugging" it in. When someone has two domains, one domain has a bought certificate from a ca provider and the other domain should use Let's Encrypt. But both domains would have, when the global flag is set, the challenge url. That's not really bad but not necessary at all, because only one domain needs it. I also think that it's easier supporting newer Let's Encrypt / certbot features when it's separated and the docker image can be easily updated and therefore adjusted to these changes. For example I used certbot-auto 0.10.1 (which is newest version) because they added the ability to remove subdomains on already created certificates via the `--expand` flag (if I remember correctly...).

I also think it's against the philosophy of micro services to add it to the listener. For example there is StartEncrypt, which is another free CA. Should StartEncrypt also be added to the swarm-listener?

The service already uses the well-formed api of Docker Flow: Proxy to create the backend and the rules in the frontend.

@raarts Yes, the part about the mount /etc/letsencrypt will be improved in the future. In the near future it's not necessary any more to mount /etc/letsencrypt but when someone wants to, for example backup the Let's Encrypt account and the certificates, he can. The image will also be slower when Let's Encrypt/certbot provides smaller official alpine images on docker hub.

**Comment by vfarcic** [comment]
@hamburml I agree. Let's keep services specific to what they do. DF Swarm Listener is in charge of passing Swarm events to other services and DF Let's Encrypt passing certificates.

**Comment by raarts** [comment]
Ok, I only suggested combining with the listener, because the proxy already has its address. So how about this:

- when a backend wants to use letsencrypt, have it specify `com.cf.certgen=letsencrypt`
- create separate image for letsencrypt (startencrypt etc) handling
- give flow-proxy the env LETSENCRYPT_ADDRESS=docker-flow-letsencrypt

The proxy would create an appropriate path for each backend that requests it

**Comment by vfarcic** [comment]
I'll close this ticket for now since https://github.com/hamburml/docker-flow-letsencrypt already fulfils the initial requirement. We can revisit the design and possible improvements later on.

**Comment by Loyz07** [comment]
Hello,

I try docker-flow-letsencrypt and it works well. Thanks @hamburml.

It may have a solution to simplify the haproxy ssl configuration file with many domains. Today here what the configuration looks like:

bind *:443 ssl crt /certs/my.domain.1.combined.pem crt /certs/my.domain.2.combined.pem crt /certs/my.domain.3.combined.pem crt /certs/my.domain.4.combined.pem crt /certs/my.domain.5.combined.pem crt /certs/my.domain.6.combined.pem etc......

I think it will be simplier to use this simple line:

bind *:443 ssl crt /certs/ 

For discussion. Thanks.

**Comment by vfarcic** [comment]
You're right. It would be easier (and better) to specify only certs directory. However, the current implementation is part of design for yet-to-be-implemented feature. The idea is to be able to specify certs globally (that part is done) but also per service (still pending). I implemented global certs with the other feature in mind. In both cases certs are stored in the same dir.
