### ISSUE TITLE
[Feature request] Endpoint to get the current configured services

### ISSUE THREAD

**Issue by bvis** [vfarcic/docker-flow-proxy#57]
In the same way we have the "remove" or "reconfigure" endpoints it would be very useful to have another endpoint to see which is the current configuration. For example:

```
curl "$(docker-machine ip node-1):8080/v1/docker-flow-proxy/get-configuration
```
Which could return a JSON encoded data with the current endpoints and some simple info about each configured backend service.

Another option could be to offer an alternative endpoint which could return the HAProxy gui data directly.

**Comment by vfarcic** [comment]
At the moment, there is an option to retrieve HAProxy config ([https://github.com/vfarcic/docker-flow-proxy#config](https://github.com/vfarcic/docker-flow-proxy#config).

Right now, I'm trying to keep the HAProxy stateless (besides mandatory HAProxy config) so I don't store information from reconfigure and remove requests. That can be changed and I can store it in memory which would be retrievable as JSON.

Initially, I thought that the actual proxy config is more valuable since it provides an accurate image of how the proxy works.

Please confirm that the config is not enough and I'll add the option to the the JSON representation of all configured services.

**Comment by bvis** [comment]
The output format is hardly parseable, then it's difficult to create a decent UI over it.
But it's enough to see what's configured, without the need of do manually the "cat" of the config file inside the container.
