### ISSUE TITLE
TCP support in swarm-mode

### ISSUE THREAD

**Issue by je-al** [vfarcic/docker-flow-proxy#70]
Hi there, is there a way to setup proxying for several TCP services?, i.e., to setup more than one frontend definition?.

There's two examples for custom templates, but it seems like the frontend only deals with setting up ACLs and then routing to an appropiate backend, making it impossible (AFAICT) to proxy more than one TCP service at the time.

Also, do the custom templates work with swarm-mode?

**Comment by getvivekv** [comment]
+1
I am also looking for the same. I need to passthrough the SSL connection and what I understand is that I can only do it if I use `mode tcp`

**Comment by vfarcic** [comment]
At the moment, one frontend serves all backends. We can change that. However, before I start adding this feature, I'd appreciate if you could give me an example configuration you'd like to accomplish. If you're not familiar with HAProxy configs, a mock config should probably do. That way, I can have a clearer objective.

The templates should work. You can specify a template in the `reconfigure` request through consulTemplateBePath and consulTemplateFePath parameters. They are still having "consul" word in their name even though with the new Swarm they are not processed through Consul. Please note that those template files need to be available either by building a new image with them inside or by exposing them as volumes. Can you please try it out and let me know if you face any problem using them.

**Comment by vfarcic** [comment]
@je-al The feature that will allow us to specify multiple frontends/backend for a single service is done and passed automated tests. There's only one task left before I release it. I need to run a few manual tests with a live service. The problem is that I don't have any service that listens to multiple ports. All those that I have are a microservice/single-process/single-port type of services.

**Comment by vfarcic** [comment]
@getvivekv Changing the mode from http to tcp is a separate issue from the request to have multiple frontend/backends. Actually, I overlooked your request completely. Can you open a new ticket for changing the mode from http to tcp? That way we can track it more easily. Also, that is fairly easy one to do so you can expect it in a day.

As a side note, you don't need tcp unless you want to use https without certificates. The proxy has the option to put a certificate into its configuration. You can see the info from [Put Certificate](https://github.com/vfarcic/docker-flow-proxy#put-certificate) section of the documentation.

**Comment by getvivekv** [comment]
Hi @vfarcic 
The way I've solved the issue with ssl passthrough is by introducing a load balancer and putting the ssl certs there. 

Example, 

*.domain.com is a CNAME record pointing to the AWS ELB -> www.elb.com (example)
The ELB has my wildcard SSL Cert installed and this is completely managed through AWS Console. The ELB is connected to 4 nodes and each of those nodes are in a swarm cluster. I know that docker swarm has its own load balancing, however I've found this method works better for us as we have to deal with a registered wildcard subdomains. This works for me very well.

**Comment by je-al** [comment]
@vfarcic actually, the kind of service that initally sparked the request is MQTT brokers (they usually support more than one protocol, e.g.: mqtt and websockets); but there's also message brokers in general, which tend to support their own binary protocol, besides HTTP, STOMP, JMS, etc.

**Comment by vfarcic** [comment]
I just added the option to specify multiple destinations for a single service. You can find the info in [release 1.133](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.133).

Assuming that I understood the request, the only thing missing would be to specify a protocol for each of those destinations (e.g. http, jms, and so on). It'll take some time since each protocol tends to have different configs. I think we'll introduce support one at a time.

P.S. Do you have a sample app and commands I could use for testing the feature?

**Comment by je-al** [comment]
I can't quite test the changes until january (sketchy internet connection), but from the docs it seems they would allow mapping more than one port to a single _service_ (swarm-mode lingo). That's use-case number one, iff you can specify an empty _servicePath_... we're dealing at the TCP level 'cause HAProxy only "knows" about HTTP. And I'm assuming it'd already allow configuring more than one TCP service, you'd assign a different frontend port and it should work (so that's use-case number two).
A separate issue is to define a BE template to deal with healthchecks and such (bunch of expects

**Comment by vfarcic** [comment]
Please let me know how it went after you played with the new feature.

Are you running the proxy inside a Swarm cluster or something else? If it's not a Swarm cluster, ignore the rest of the message.

In case it's a Swarm cluster, I'm not sure there is a need for health checks since the proxy does not care about service instances. It forwards requests to a Swarm service through Overlay network. Load balancing is performed by Docker network and, among other things, it already includes health checks. In such a setting, the only advantage of having health checks is to check whether the whole service (all instances/replicas) are down. HAProxy, on the other hand, is designed to check whether an instance is down or not.

**Comment by je-al** [comment]
Oh, the proxy is using the VIP? What if I specify the endpoint mode to be dnsrr? It's kind of a hack, but being able to actually point to all of the containers allows for custom healthchecks where you check for the current "leader" of a service (I'm thinking of Redis).

**Comment by vfarcic** [comment]
It does not necessarily need to use VIP. At the beginning, the proxy relied on ports and IPs stored in Consul (could be extended to other key/value stores. That meant that something like Registrator was needed to register info before the proxy could pick it up.

When Docker released Swarm Mode, it also released new API that exposes info about service. That's when I created *Docker Flow: Swarm Listener* that uses that API to provide the info proxy needs.

The problem is that Swarm's API has info about service, not its replicas. There is no way (as far as I know), to get the info about Overlay network IPs of all the replicas. At least, not through Swarm API. So, the only viable option is to use VIP and forward requests to Swarm service and let networking do load balancing. The alternative would be to query tasks.[SERVICE_NAME] endpoint. That gives all the IPs. I can add that as a separate mode to run the proxy. In that case, proxy health checks would be needed.

Please let me know if something like that would solve your problems. (proxy does load balancing and forwards directly to a replica). If it does, can you please open a separate ticket and let me know how urgent it is (low on manpower / trying to prioritize).

As for templates, that should not be a problem. It's a relatively easy thing to do. It should be available in a few days.

**Comment by vfarcic** [comment]
I added the information about [templates](https://github.com/vfarcic/docker-flow-proxy#templates). That should allow you to control proxy config and add any protocol you might need. Please try it out and let me know whether it fits your use case or if you have any problem using it.

The idea behind templates is to act as a way to add features that are currently not supported. Please let me know if there is a missing feature you think would be useful to add as [reconfigure parameter](https://github.com/vfarcic/docker-flow-proxy#reconfigure) instead fiddling with templates.

**Comment by je-al** [comment]
So, using the following configuration:

```
docker service create \
  --name ${ESERVICE}-proxy \
  --network ${NETWORK} \
  --restart-condition any \
  --constraint 'node.role == manager' \
  --publish 8080:8080 \
  --publish 1883:1883 \
  --publish 8083:8083 \
  --mount 'target=/var/run/docker.sock,source=/var/run/docker.sock,type=bind' \
  --env 'MODE=swarm' \
  ${REGISTRY}vfarcic/docker-flow-proxy:1.134
```
and submitting:

```
curl -i "$(docker-machine ip node-0):8080/v1/docker-flow-proxy/reconfigure?serviceName=emq&servicePath.1=/&port.1=1883&srcPort.1=1883&servicePath.2=/&port.8083=8083&srcPort.2=8083"
```

yields:

```
{"Status":"OK","Message":"","ServiceName":"emq","AclName":"","ServiceColor":"","ServiceDomain":null,"ServiceCert":"","OutboundHostname":"","ConsulTemplateFePath":"","ConsulTemplateBePath":"","PathType":"","SkipCheck":false,"Mode":"swarm","HttpsPort":0,"Distribute":false,"Users":null,"ReqRepSearch":"","ReqRepReplace":"","ReqPathSearch":"","ReqPathReplace":"","TemplateFePath":"","TemplateBePath":"","ServiceDest":[{"Port":"1883","Path":["/"],"SrcPort":1883}]}
```

and the following configuration:

```
frontend services
    bind *:80
    bind *:443
    mode http



    acl url_emq1883 path_beg /
    acl srcPort_emq1883 dst_port 1883
    use_backend emq-be1883 if url_emq1883 srcPort_emq1883


backend emq-be1883
    mode http
    server emq emq:1883
```

Two clear issues, namely:
- The second service port definition isn't being picked up.
- There's no way for this to work for non HTTP services because of the path being analyzed (I guess that's what you meant by adding support for other protocols), and even if that weren't the case, the only frontend defined isn't even listening on the port that's used as a condition to match the backend.

What am I doing wrong?

**Comment by vfarcic** [comment]
*The second service port definition isn't being picked up.*

You put 8083 instead 2 for the second port. Can you try it again with the command that follows?

```bash
curl -i "$(docker-machine ip node-0):8080/v1/docker-flow-proxy/reconfigure?serviceName=emq&servicePath.1=/&port.1=1883&srcPort.1=1883&servicePath.2=/&port.2=8083&srcPort.2=8083"
```

*There's no way for this to work for non HTTP services because of the path being analyzed (I guess that's what you meant by adding support for other protocols)*

That's correct. At the moment, the proxy supports only HTTP. I'll add the support for other protocols later. It would help if you can open a separate ticket for that so that we can track it.

*and even if that weren't the case, the only frontend defined isn't even listening on the port that's used as a condition to match the backend.*

You'll need to define env. variable `BIND_PORTS` as well. By default, the proxy listens only to ports 80 and 443. Take a look at [Environment Variables](https://github.com/vfarcic/docker-flow-proxy#environment-variables) section.

**Comment by vfarcic** [comment]
Reopening the issue in case it doesn't work after the additional instructions.

**Comment by je-al** [comment]
@vfarcic, sorry about that, I just edited the comment after noticing a few things, and reading on missing options from other issues...

**Comment by vfarcic** [comment]
It is fairly straightforward to add tcp support. I'm on a trip this week so I'm not sure whether I'll get a bit of free time to do it in the next few days. If should be done during the weekend, if not before.

Can you give me a hand? It would be helpful if you could send me a command to create a tcp service and a command or two to test whether it works. There's no need to involve proxy in those commands.

**Comment by je-al** [comment]
Why, almost any service will do; e.g. Redis:
```
docker run -it --port --publish 6379:6379 --rm redis:3.2
```
and this expect script:
```
#!/usr/bin/env expect
spawn nc -w 2 $env(ADDR) $env(PORT)

set EC 0

send "PING\r\n"
expect "+PONG"
send "QUIT\r\n"
expect "+OK"
exit $EC
```
run it like this:
```
ADDR=localhost PORT=6379 ./redis_check
```

which should return 0 only when it interacts correctly with the service.

**Comment by vfarcic** [comment]
Please see the [release 1.135](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.135) for more info.
