### ISSUE TITLE
Support for internal services only, ie. expose service on 127.0.0.1 or on local network interface only

### ISSUE THREAD

**Issue by virtuman** [vfarcic/docker-flow-proxy#71]
Our infrastructure consists of multiple hosts that run docker-based services, and bare-metal hosts that run long-running services.

All of our servers have public NIC cards and local-only network cards. 
Is it possible to start up services using docker-flow-proxy that would expose port on the local network only (ie. REDIS, Memcached, etc.) that could be accessed by non-docker-members that sit on same local network? Or maybe it's possible to set up white lists of hosts that can access that particular service or not?

How would the routing work in this case? Would it know which NIC to use to get to the right host? Ie. hosts should expose service on local card only or will it expose through all interfaces but make it accessible by white-listed hosts only?

Thank you.

**Comment by vfarcic** [comment]
When you expose ports of a service, Docker does not really care whether that's internal or external network. Normally, you'd accomplish that with a security group that would control who has access to a port.

There is the option in the proxy to specify host(s) that can access certain service. However, that is not really secure since anyone can fake a host.

**Comment by vfarcic** [comment]
This issue is more related Docker networking so I'll close this ticket. Please reopen if you disagree.
